site_name: Data Structures
nav: 
  - Sorting: 
    - BubbleSort: sorting/bubblesort.md

theme: readthedocs

plugins:
  - search
  - mermaid2

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js